### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by superbobry** [d3/d3-dsv#18]
Some CSV files begin with comments and, while these can be stripped in 90% of the cases, sometimes the comments can actually be useful, e.g. when holding some metadata. 

Do you have any plans to extend the API to handle comments? Currently the parser simply treats them as headers:

```js
> d3.dsvFormat(",").parse("#foo\n#bar\n1,2")
[
  {"#foo": "#bar"},
  {"#foo": "1"}
]
```

**Comment by mbostock** [comment]
Sorry, but I have no plans to implement comment stripping or additional metadata parsing; these features aren’t covered by [RFC 4180](https://tools.ietf.org/html/rfc4180), and I’m not aware of a widely-accepted RFC that includes these features. If there is one, I’d review a pull request that implements such functionality, but if not, it’d probably be best implemented as a fork of this library or as a pre-processing step before parsing.
