### ISSUE TITLE
How to use Command Line Reference

### ISSUE THREAD

**Issue by xswei** [d3/d3-dsv#37]
I read the api document about "d3-dsv", but don't know how to use command line, is need other package?

**Comment by msforest** [comment]
`npm install -g d3-dsv`
u can use cmd with `csv2json test.csv -o test.json` 

`npm install -S d3-dsv`
u can use cmd with `./node_modules/.bin/csv2json test.csv -o test.json`

**Comment by mbostock** [comment]
Did you see the Command Line Reference?

https://github.com/d3/d3-dsv/blob/master/README.md#command-line-reference
