### ISSUE TITLE
How to read csv in nodejs

### ISSUE THREAD

**Issue by AbhimanyuAryan** [d3/d3-dsv#38]
I want to read CSV in node not use browser. How would I do that?

**Comment by curran** [comment]
You can use the Node.js `fs` module to read the text of a CSV file, then pass that string into `d3.csvParse`.

**Comment by mbostock** [comment]
Right, this library doesn’t support streaming input, so usage in the browser and Node is essentially the same. You have a string of CSV, you pass it to d3.csvParse, and you get back an array of objects.
