### ISSUE TITLE
Make d3.autoType the default row accessor.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-dsv#43]
This will require a major version bump, but I think it’d be good to make d3.autoType the default row accessor for *dsv*.parse and *dsv*.parseRows. If you want to disable automatic type inference, you can pass the identity function (`d => d`) as the row function.

**Comment by Fil** [comment]
Yes!

**Comment by Fil** [comment]
I'm not totally sure of the consequences [here](https://github.com/d3/d3-dsv/blob/master/src/dsv.js#L67), isn't it that we can now inline objectConverter?

**Comment by Fil** [comment]
I simply added f=autoType to parse and parseRows, and got 77 test failing 😱 — I started to go through them, but for so many of them,  I'm at a loss whether we want to change them or keep the old test with `f=null`.


Examples:

~~~
tape("csvParse(string) does not strip whitespace", function(test) {
  test.deepEqual(dsv.csvParse("a,b,c\n 1, 2 ,3 "), table([{a: " 1", b: " 2 ", c: "3 "}], ["a", "b", "c"]));
  test.end();
});
~~~
autoType returns numbers 1, 2, 3.

We could amend the test to "csvParse(string, null) does not strip whitespace"; or test that we get 1, 2, 3.  (There is an autoType test saying it should return a number.)


~~~
tape("csvParse(string) treats empty fields as the empty string", function(test) {
  test.deepEqual(dsv.csvParse("a,b,c\n1,,3"), table([{a: 1, b: "", c: 3}], ["a", "b", "c"]));
  test.end();
});
~~~

autoType returns `b:null`

etc.

**Comment by mbostock** [comment]
I’m not inclined to change this behavior for d3 v6, because even though it might be nice, it’s a pretty significant backwards-incompatibility shift.

**Comment by Fil** [comment]
I'd argue that, unless you're not 100% convinced it's the right decision,
the earlier the better — especially since a lot of examples in the wild are
still with d3v3.

I've done the PR anyhow — no worries if it's merged only later or not at
all.

**Comment by mbostock** [comment]
I’m inclined to keep the status quo for the foreseeable future.
