### ISSUE TITLE
Add documentation about CSP incompatibility

### ISSUE THREAD

**Issue by tdelmas** [d3/d3-dsv#66]
It's important to highlight methods not compatible with a strong Content-Security-Policy (i.e. without `unsafe-eval`).

In the same wait it's documented in https://github.com/d3/d3-dsv#content-security-policy 

It should be documented in https://github.com/d3/d3-dsv/blob/master/README.md#csvParse : https://github.com/d3/d3-dsv/issues/65

**Comment by mbostock** [comment]
I don’t see a need to repeat the CSP documentation that already exists in the README, but feel free to send a PR with suggested edits.
