### ISSUE TITLE
Potential performance issue - Columns property added to returned array from dsv.parse could lose browser engine optimization on array operations

### ISSUE THREAD

**Issue by idatatalks** [d3/d3-dsv#88]
Per https://javascript.info/array, adding a non-numeric property to an array is one way of misuse JS array, which could lead to the engine see this array as a regular object and turn off the internal optimization on array operations.
If that's true, adding non-numeric property "Columns" to the returned array from dsv.parse breaks the rule.

The ways to misuse an array from https://javascript.info/array are pasted as below:
> Add a non-numeric property like arr.test = 5.
> Make holes, like: add arr[0] and then arr[1000] (and nothing between them).
> Fill the array in the reverse order, like arr[1000], arr[999] and so on.

I couldn't find array misuse descriptions in other JS books or MDN except https://javascript.info, so I'm not quite sure if it's still applied in latest engines.

**Comment by mbostock** [comment]
You can call parseRows if you are concerned with performance. I have not found this to be an issue in practice.
