### ISSUE TITLE
Column data will be lost if the column name is the same

### ISSUE THREAD

**Issue by jasmine-song** [d3/d3-dsv#91]
```console.log(d3.tsvParse("bar\tbar\n1\t2"))```
![image](https://user-images.githubusercontent.com/44150070/178218922-5aa69cd8-ec1e-4a51-85e5-03378d3e4cab.png)
If there is the same column name, the data in the previous column is overwritten by the following column
How do I keep data with the same column name

**Comment by Fil** [comment]
As per the documentation:

> If the column names are not unique, only the last value is returned for each name; to access all values, use [dsv.parseRows](https://github.com/d3/d3-dsv#dsv_parseRows) instead (see [example](https://observablehq.com/@d3/parse-csv-with-duplicate-column-names)).
