### ISSUE TITLE
`objectConverter` can work without `Function`.

### ISSUE THREAD

**Issue by KaKi87** [d3/d3-dsv#94]
Hello,

The [`objectConverter` function](https://github.com/d3/d3-dsv/blob/6d96d6c0c70add67ec3869a22b3bbcd072ce328b/src/dsv.js#L7), if I understand it correctly, takes an array of keys, and returns a function, that takes an array of values, and returns an object.

I'm guessing preserving IE11 compatibility was the goal, so here's an alternative that still does, while working without `Function` :

```js
function objectConverter(columns){
    return function(d){
        var o = {};
        columns.forEach(function(name, i){
            o[name] = d[i];
        });
        return o;
    };
}
```

And, for future reference, here's another one that uses the latest syntax :
```js
const objectConverter = columns => d => Object.fromEntries(columns.map((name, i) => [name, d[i]]));
```

Thanks

**Comment by mbostock** [comment]
Related https://github.com/d3/d3-dsv/pull/26#issuecomment-298638569 #80 #87.
